// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend_projetoairsoft.Models;

namespace backend_projetoairsoft.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("backend_projetoairsoft.Models.Equipe", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Jogador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nome");

                    b.ToTable("Equipe");
                });

            modelBuilder.Entity("backend_projetoairsoft.Models.Evento", b =>
                {
                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jogador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("localRua")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Titulo");

                    b.HasIndex("localRua");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("backend_projetoairsoft.Models.Jogador", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Modalidade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nome");

                    b.ToTable("Jogador");
                });

            modelBuilder.Entity("backend_projetoairsoft.Models.Jogo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("equipeNome")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("equipeNome");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("backend_projetoairsoft.Models.Local", b =>
                {
                    b.Property<string>("Rua")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("UF")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Rua");

                    b.ToTable("Local");
                });

            modelBuilder.Entity("backend_projetoairsoft.Models.Evento", b =>
                {
                    b.HasOne("backend_projetoairsoft.Models.Local", "local")
                        .WithMany()
                        .HasForeignKey("localRua");

                    b.Navigation("local");
                });

            modelBuilder.Entity("backend_projetoairsoft.Models.Jogo", b =>
                {
                    b.HasOne("backend_projetoairsoft.Models.Equipe", "equipe")
                        .WithMany()
                        .HasForeignKey("equipeNome");

                    b.Navigation("equipe");
                });
#pragma warning restore 612, 618
        }
    }
}
